apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
    component: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
        component: paymentservice
    spec:
      containers:
      - name: payment
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        env:
        - name: PAYMENT_PORT
          value: "8085"
        - name: PAYMENT_ADDR
          value: "payment:8085"
        - name: OTEL_SERVICE_NAME
          value: "payment-service"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otelcol:4317"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=payment-service,service.namespace=opentelemetry-demo,service.version=1.12.0"
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 150Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5