apiVersion: v1
kind: Service
metadata:
  name: payment
  
  labels:
    app: payment
    component: paymentservice
spec:
  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 80
    name: http
  selector:
    app: payment