apiVersion: v1
kind: Service
metadata:
  name: frontend-proxy
  namespace: opentelemetry-demo
  labels:
    app: frontend-proxy
    component: frontend-proxy
spec:
  selector:
    app: frontend-proxy
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer