

networks:
  otel-demo:
    driver: bridge

services:
  # OpenTelemetry Collector
  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-col
    command: ["--config=/etc/otelcol-contrib/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    networks:
      - otel-demo

  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    networks:
      - otel-demo

  ad:
    image: sdhivya/ad-service:latest
    container_name: ad
    environment:
      - AD_PORT=8081
      - AD_ADDR=ad:8081
      - OTEL_SERVICE_NAME=ad-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
    ports:
      - "8081:8081"
    networks:
      - otel-demo
    depends_on:
      - otelcol

  cart:
    image: sdhivya/cart-service:latest
    container_name: cart
    environment:
      - CART_PORT=8082
      - CART_ADDR=cart:8082
      - VALKEY_ADDR=valkey:6379
      - OTEL_SERVICE_NAME=cart-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
    ports:
      - "8082:8082"
    networks:
      - otel-demo
    depends_on:
      - otelcol
      - valkey

  flagd:
    image: ghcr.io/open-feature/flagd:latest
    container_name: flagd
    environment:
      - FLAGD_LOG_LEVEL=debug
      - FLAGD_OTEL_COLLECTOR_URI=http://otelcol:4317
      - OTEL_SERVICE_NAME=flagd
    ports:
      - "8013:8013"
    volumes:
      - ./microservices/flagd/demo.flagd.json:/etc/flagd/demo.flagd.json
    command: ["start", "--uri", "file:///etc/flagd/demo.flagd.json"]
    networks:
      - otel-demo

  currency:
    image: sdhivya/currency-service:latest
    container_name: currency
    environment:
      - CURRENCY_PORT=8084
      - CURRENCY_ADDR=currency:8084
      - VERSION=1.0.0
      - OTEL_SERVICE_NAME=currency-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
    ports:
      - "8084:8084"
    networks:
      - otel-demo
    depends_on:
      - otelcol

  checkout:
    image: sdhivya/checkout-service:latest
    container_name: checkout
    environment:
      - CHECKOUT_PORT=8083
      - CHECKOUT_ADDR=checkout:8083
      - CART_SERVICE_ADDR=cart:8082
      - CURRENCY_SERVICE_ADDR=currency:8084
      - PAYMENT_SERVICE_ADDR=payment:8085
      - SHIPPING_SERVICE_ADDR=shipping:8088
      - SHIPPING_ADDR=shipping:8088
      - PRODUCT_CATALOG_ADDR=product-catalog:8086
      - RECOMMENDATION_SERVICE_ADDR=recommendation:1010
      - AD_SERVICE_ADDR=ad:8081
      - OTEL_SERVICE_NAME=checkout-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
    ports:
      - "8083:8083"
    networks:
      - otel-demo
    depends_on:
      - otelcol
      - cart
      - currency
      - payment
      - shipping
      - product-catalog
      - recommendation
      - ad

  payment:
    image: sdhivya/payment-service:latest
    container_name: payment
    environment:
      - PAYMENT_PORT=8085
      - PAYMENT_ADDR=payment:8085
      - OTEL_SERVICE_NAME=payment-service
    ports:
      - "8085:8085"
    networks:
      - otel-demo

  product-catalog:
    image: sdhivya/product-catalog-service:latest
    container_name: product-catalog
    environment:
      - PRODUCT_CATALOG_PORT=8086
      - PRODUCT_CATALOG_ADDR=product-catalog:8086
      - OTEL_SERVICE_NAME=product-catalog-service
    ports:
      - "8086:8086"
    networks:
      - otel-demo

  recommendation:
    image: sdhivya/recommendation-service:latest
    container_name: recommendation
    environment:
      - RECOMMENDATION_PORT=1010
      - RECOMMENDATION_ADDR=recommendation:1010
      - PRODUCT_CATALOG_ADDR=product-catalog:8086
      - OTEL_SERVICE_NAME=recommendation-service
    ports:
      - "1010:1010"
    networks:
      - otel-demo
    depends_on:
      - product-catalog

  shipping:
    image: sdhivya/shipping-service:latest
    container_name: shipping
    environment:
      - SHIPPING_PORT=8088
      - SHIPPING_ADDR=shipping:8088
      - OTEL_SERVICE_NAME=shipping-service
    ports:
      - "8088:8088"
    networks:
      - otel-demo

  frontend:
    build:
      context: ./microservices/frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - FRONTEND_PORT=8080
      - FRONTEND_ADDR=0.0.0.0:8080
      - AD_SERVICE_ADDR=ad:8081
      - CART_SERVICE_ADDR=cart:8082
      - CHECKOUT_SERVICE_ADDR=checkout:8083
      - CURRENCY_SERVICE_ADDR=currency:8084
      - PAYMENT_SERVICE_ADDR=payment:8085
      - PRODUCT_CATALOG_ADDR=product-catalog:8086
      - RECOMMENDATION_SERVICE_ADDR=recommendation:1010
      - SHIPPING_SERVICE_ADDR=shipping:8088
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - OTEL_SERVICE_NAME=frontend-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - NEXT_PUBLIC_OTEL_SERVICE_NAME=frontend-service
      - NEXT_PUBLIC_PLATFORM_URL=http://13.203.200.147:8080
      - WEB_OTEL_SERVICE_NAME=frontend-web
      - PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://13.203.200.147:8080/otlp-http/v1/traces
    ports:
      - "8080:8080"
    networks:
      - otel-demo
    depends_on:
      - otelcol
      - flagd
      - cart
      - currency
      - payment
      - checkout
      - ad
      - recommendation
      - shipping
      - product-catalog

