networks:
  default:
    name: opentelemetry-demo
    driver: bridge

services:
  frontend:
    image: ghcr.io/open-telemetry/demo:latest-frontend
    container_name: frontend
    build:
      context: ./
      dockerfile: microservices/frontend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      ad:
        condition: service_started
      cart:
        condition: service_started
      checkout:
        condition: service_started
    
  cart:
    image: ghcr.io/open-telemetry/demo:latest-cart
    container_name: cart
    build:
      context: ./
      dockerfile: microservices/cart/src/Dockerfile
    ports:
      - "7070:7070"

  checkout:
    image: ghcr.io/open-telemetry/demo:latest-checkout
    container_name: checkout
    build:
      context: ./
      dockerfile: microservices/checkout/Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      cart:
        condition: service_started
      payments:
        condition: service_started

  payment:
    image: ghcr.io/open-telemetry/demo:latest-payment
    container_name: payment
    build:
      context: ./
      dockerfile: microservices/payment/Dockerfile
    ports:
      - "50051:50051"

  ad:
    image: ghcr.io/open-telemetry/demo:latest-ad
    container_name: ad
    build:
      context: ./
      dockerfile: microservices/ad/Dockerfile
    ports:
      - "9555:9555"