version: "3.9"

networks:
  otel-demo:
    driver: bridge

services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    networks:
      - otel-demo

  frontend:
    image: sdhivya/frontend-service:latest
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - AD_SERVICE_ADDR=ad:8081
      - CART_SERVICE_ADDR=cart:8082
      - CHECKOUT_SERVICE_ADDR=checkout:8083
      - PAYMENT_SERVICE_ADDR=payment:8085
      - PRODUCT_CATALOG_ADDR=product-catalog:8086
      - RECOMMENDATION_SERVICE_ADDR=recommendation:1010
      - SHIPPING_SERVICE_ADDR=shipping:8088
    networks:
      - otel-demo
    depends_on:
      - ad
      - cart
      - checkout
      - payment
      - product-catalog
      - recommendation
      - shipping

  ad:
    image: sdhivya/ad-service:latest
    container_name: ad
    ports:
      - "8081:8081"
    networks:
      - otel-demo
    depends_on:
      - recommendation

  cart:
    image: sdhivya/cart-service:latest
    container_name: cart
    ports:
      - "8082:8082"
    environment:
      - VALKEY_ADDR=valkey:6379
    networks:
      - otel-demo

  checkout:
    image: sdhivya/checkout-service:latest
    container_name: checkout
    ports:
      - "8083:8083"
    environment:
      - CART_ADDR=cart:8082
      - PAYMENT_ADDR=payment:8085
    networks:
      - otel-demo
    depends_on:
      - cart
      - payment

  payment:
    image: sdhivya/payment-service:latest
    container_name: payment
    ports:
      - "8085:8085"
    networks:
      - otel-demo

  product-catalog:
    image: sdhivya/product-catalog-service:latest
    container_name: product-catalog
    ports:
      - "8086:8086"
    networks:
      - otel-demo

  recommendation:
    image: sdhivya/recommendation-service:latest
    container_name: recommendation
    ports:
      - "1010:1010"
    environment:
      - PRODUCT_CATALOG_ADDR=product-catalog:8086
    networks:
      - otel-demo
    depends_on:
      - product-catalog

  shipping:
    image: sdhivya/shipping-service:latest
    container_name: shipping
    ports:
      - "8088:8088"
    networks:
      - otel-demo
