networks:
  default:
    name: otel-demo
    driver: bridge

services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
  frontend:
    image: sdhivya/frontend-service:latest
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - FRONTEND_PORT=8080
      - OTEL_SERVICE_NAME=frontend
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - CART_ADDR=cart:7070
      - AD_ADDR=ad:5050
      - CHECKOUT_ADDR=checkout:8081
      - RECOMMENDATION_ADDR=recommendation:8082

    depends_on:
      ad:
        condition: service_started
      cart:
        condition: service_started
      checkout:
        condition: service_started
      recommendation:
        condition: service_started

    volumes:
      - frontend-data:/app/data  
  cart:
    image: sdhivya/cart-service:latest
    container_name: cart
    ports:
      - "7070:7070"
    environment:
      - VALKEY_ADDR=valkey:6379
      - CART_PORT=7070
      - OTEL_SERVICE_NAME=cart
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    depends_on:
      valkey:
        condition: service_started

    volumes:
      - cart-data:/app/data
  checkout:
    image: sdhivya/checkout-service:latest
    container_name: checkout
    ports:
      - "8081:8081"
    environment:
      - CHECKOUT_PORT=8081
      - OTEL_SERVICE_NAME=checkout
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none

    depends_on:
      cart:
        condition: service_started
      payment:
        condition: service_started

        
    volumes:
       - checkout-data:/app/data
  payment:
    image: sdhivya/payment-service:latest
    container_name: payment
    ports:
      - "50051:50051"
    environment:
      - PAYMENT_PORT=50051
      - OTEL_SERVICE_NAME=payment
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    volumes:
      - payment-data:/app/data
  ad:
    image: sdhivya/ad-service:latest
    container_name: ad
    ports:
      - "5050:5050"
    environment:
      - AD_PORT=5050
      - OTEL_SERVICE_NAME=ad
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    volumes:
      - ad-data:/app/data


  recommendation:
    image: sdhivya/recommendation-service:latest
    container_name: recommendation
    ports:
      - "8082:8082"
    environment:
      - OTEL_SERVICE_NAME=recommendation
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - RECOMMENDATION_PORT=8082
    volumes:
      - recommendation-data:/app/data
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "55681:55681"
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13133/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:

      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:

      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
volumes:


  frontend-data:
  cart-data:
  checkout-data:
  payment-data:
  ad-data:
  recommendation-data:
  valkey-data:
  otel-collector-data:
  