version: "3.9"

networks:
  otel-demo:
    driver: bridge

services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    networks:
      - otel-demo

  frontend:
    image: sdhivya/frontend-service:latest
    container_name: frontend
    ports:
      - "8080:7070"
    networks:
      - otel-demo
    depends_on:
      - ad
      - cart
      - checkout

  cart:
    image: sdhivya/cart-service:latest
    container_name: cart
    ports:
      - "7070:9055"
    environment:
      - VALKEY_ADDR=valkey:6379
    networks:
      - otel-demo

  checkout:
    image: sdhivya/checkout-service:latest
    container_name: checkout
    ports:
      - "8081:9097"
    environment:
      - CHECKOUT_PORT=9097
    networks:
      - otel-demo
    depends_on:
      - cart
      - payment

  payment:
    image: sdhivya/payment-service:latest
    container_name: payment
    ports:
      - "50051:6060" # host:container
    environment:
      - PAYMENT_PORT=6060
    networks:
      - otel-demo

  ad:
    image: sdhivya/ad-service:latest
    container_name: ad
    ports:
      - "5050:9099"
    networks:
      - otel-demo

  recommendation:
    image: sdhivya/recommendation-service:latest
    container_name: recommendation
    ports:
      - "8082:1010"
    environment:
      - OTEL_SERVICE_NAME=recommendation
      - PRODUCT_CATALOG_ADDR=fake_catalog:8080 # temporary if catalog not available
    networks:
      - otel-demo
