apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app: currency
    component: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
        component: currencyservice
    spec:
      containers:
      - name: currency
        image: sdhivya/currency-service:latest
        ports:
        - containerPort: 8084
          name: http
        env:
        - name: CURRENCY_PORT
          value: "8084"
        - name: CURRENCY_ADDR
          value: "currency:8084"
        - name: VERSION
          value: "1.0.0"
        - name: OTEL_SERVICE_NAME
          value: "currency-service"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otelcol:4317"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=currency-service,service.namespace=opentelemetry-demo,service.version=1.12.0"
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 150Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 5
          periodSeconds: 5