apiVersion: v1
kind: Service
metadata:
  name: currency
  
  labels:
    app: currency
    component: currencyservice
spec:
  type: ClusterIP
  ports:
  - port: 8084
    targetPort: 8084
    name: http
  selector:
    app: currency