apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: opentelemetry-demo
  labels:
    app: valkey
    component: database
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: valkey
  selector:
    app: valkey