apiVersion: v1
kind: Service
metadata:
  name: recommendation
  namespace: opentelemetry-demo
  labels:
    app: recommendation
    component: recommendation
spec:
  selector:
    app: recommendation
  ports:
  - name: http
    port: 8087
    targetPort: 8087
    protocol: TCP
  type: ClusterIP