apiVersion: v1
kind: Service
metadata:
  name: shipping
 
  labels:
    app: shipping
    component: shipping
spec:
  selector:
    app: shipping
  ports:
  - name: http
    port: 8088
    targetPort: 8088
    protocol: TCP
  type: ClusterIP