apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: opentelemetry-demo
  labels:
    app: cart
    component: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
        component: cartservice
    spec:
      containers:
      - name: cart
        image: sdhivya/cart-service:latest
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: CART_PORT
          value: "8082"
        - name: CART_ADDR
          value: "cart:8082"
        - name: VALKEY_ADDR
          value: "valkey:6379"
        - name: OTEL_SERVICE_NAME
          value: "cart-service"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otelcol:4317"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=cart-service,service.namespace=opentelemetry-demo,service.version=1.12.0"
        resources:
          limits:
            cpu: 300m
            memory: 400Mi
          requests:
            cpu: 150m
            memory: 200Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
