apiVersion: v1
kind: Service
metadata:
  name: cart

  labels:
    app: cart
    component: cartservice
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 80
    name: http
  selector:
    app: cart