apiVersion: v1
kind: Service
metadata:
  name: ad
  namespace: opentelemetry-demo
  labels:
    app: ad
    component: adservice
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8080
    name: http
  selector:
    opentelemetry.io/name: opentelemetry-demo-adservice