apiVersion: v1
kind: Service
metadata:
  name: ad
  
  labels:
    app: ad
    component: adservice
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 80
    name: http
  selector:
    opentelemetry.io/name: opentelemetry-demo-adservice