apiVersion: v1
kind: Service
metadata:
  name: flagd
  
  labels:
    app: flagd
    component: flagd
spec:
  type: ClusterIP
  ports:
  - port: 8013
    targetPort: 8013
    name: http
  selector:
    app: flagd