apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  labels:
    app: checkout
    component: checkoutservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
        component: checkoutservice
    spec:
      containers:
      - name: checkout
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        env:
        - name: CHECKOUT_PORT
          value: "8083"
        - name: CHECKOUT_ADDR
          value: "checkout:8083"
        - name: CART_SERVICE_ADDR
          value: "cart:8082"
        - name: CART_ADDR
          value: "cart:8082"
        - name: CURRENCY_SERVICE_ADDR
          value: "currency:8084"
        - name: CURRENCY_ADDR
          value: "currency:8084"
        - name: PAYMENT_SERVICE_ADDR
          value: "payment:8085"
        - name: PAYMENT_ADDR
          value: "payment:8085"
        - name: SHIPPING_SERVICE_ADDR
          value: "shipping:8088"
        - name: SHIPPING_ADDR
          value: "shipping:8088"
        - name: PRODUCT_CATALOG_ADDR
          value: "product-catalog:8086"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendation:8087"
        - name: AD_SERVICE_ADDR
          value: "ad:8081"
        - name: OTEL_SERVICE_NAME
          value: "checkout-service"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otelcol:4317"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=checkout-service,service.namespace=opentelemetry-demo,service.version=1.12.0"
        resources:
          limits:
            cpu: 300m
            memory: 400Mi
          requests:
            cpu: 150m
            memory: 200Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5