apiVersion: v1
kind: Service
metadata:
  name: checkout
  
  labels:
    app: checkout
    component: checkoutservice
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    name: http
  selector:
    app: checkout