apiVersion: v1
kind: Service
metadata:
  name: email
  labels:
    app: email
    component: emailservice
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 6060
    targetPort: 6060
  selector:
    app: email