apiVersion: v1
kind: Service
metadata:
  name: frontend
 
  labels:
    app: frontend
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: frontend