apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-provider
  labels:
    app: image-provider
    component: image-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-provider
  template:
    metadata:
      labels:
        app: image-provider
        component: image-provider
    spec:
      containers:
      - name: image-provider
        image: ghcr.io/open-telemetry/demo:1.12.0-imageprovider
        ports:
        - containerPort: 80
          name: http
        env:
        - name: IMAGE_PROVIDER_PORT
          value: "80"
        - name: OTEL_SERVICE_NAME
          value: "imageprovider"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otelcol:4317"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://otelcol:4317"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=imageprovider,service.namespace=opentelemetry-demo,service.version=1.12.0"
        - name: ENVOY_PORT
          value: "8080"
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5