apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-provider
  labels:
    app: image-provider
    component: image-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-provider
  template:
    metadata:
      labels:
        app: image-provider
        component: image-provider
    spec:
      initContainers:
      - name: setup-files
        image: ghcr.io/open-telemetry/demo:1.12.0-imageprovider
        command: ["/bin/sh"]
        args:
        - -c
        - |
          # Create proper directory structure in /static
          mkdir -p /shared-static/images /shared-static/icons /shared-static/images/products
          
          # Copy original files to shared volume
          if [ -d /static ]; then
            cp -r /static/* /shared-static/
          fi
          
          # Copy images to the correct locations
          if [ -f /shared-static/Banner.png ]; then
            cp /shared-static/Banner.png /shared-static/images/
          fi
          if [ -f /shared-static/opentelemetry-demo-logo.png ]; then
            cp /shared-static/opentelemetry-demo-logo.png /shared-static/images/
          fi
          
          # Copy all product images if they exist
          if [ -d /shared-static/products ]; then
            cp /shared-static/products/* /shared-static/images/products/ 2>/dev/null || true
          fi
          
          # Create basic SVG icons
          cat > /shared-static/icons/Chevron.svg << 'EOF'
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M9 18L15 12L9 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          EOF
          
          cat > /shared-static/icons/CartIcon.svg << 'EOF'
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M3 3H5L5.4 5M7 13H17L21 5H5.4M7 13L5.4 5M7 13L4.7 15.3C4.3 15.7 4.6 16.5 5.1 16.5H17M17 13V17A2 2 0 0 1 15 19H9A2 2 0 0 1 7 17V13" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          EOF
          
          echo "Files setup completed!"
          echo "Contents of /shared-static:"
          ls -la /shared-static/
          echo "Contents of /shared-static/images:"
          ls -la /shared-static/images/
          echo "Contents of /shared-static/icons:"
          ls -la /shared-static/icons/
        volumeMounts:
        - name: static-volume
          mountPath: /shared-static
      containers:
      - name: image-provider
        image: ghcr.io/open-telemetry/demo:1.12.0-imageprovider
        ports:
        - containerPort: 80
          name: http
        env:
        - name: IMAGE_PROVIDER_PORT
          value: "80"
        - name: OTEL_SERVICE_NAME
          value: "imageprovider"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otelcol:4317"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://otelcol:4317"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=imageprovider,service.namespace=opentelemetry-demo,service.version=1.12.0"
        - name: ENVOY_PORT
          value: "8080"
        volumeMounts:
        - name: static-volume
          mountPath: /static
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: static-volume
        emptyDir: {}