apiVersion: v1
kind: Service
metadata:
  name: image-provider
  namespace: opentelemetry-demo
  labels:
    app: image-provider
    component: image-provider
spec:
  selector:
    app: image-provider
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP