apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  namespace: opentelemetry-demo
  labels:
    app: product-catalog
    component: productcatalog
spec:
  selector:
    app: product-catalog
  ports:
  - name: http
    port: 8086
    targetPort: 8086
    protocol: TCP
  type: ClusterIP