apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
  labels:
    app: otelcol
    component: opentelemetry-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcol
  template:
    metadata:
      labels:
        app: otelcol
        component: opentelemetry-collector
    spec:
      serviceAccountName: opentelemetry-demo
      containers:
      - name: otelcol
        image: otel/opentelemetry-collector-contrib:latest
        args: ["--config=/etc/otelcol-contrib/otel-collector-config.yaml"]
        ports:
        - containerPort: 1888
          name: pprof
        - containerPort: 8888
          name: prometheus
        - containerPort: 8889
          name: prom-exporter
        - containerPort: 13133
          name: health-check
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        - containerPort: 55679
          name: zpages
        env:
        - name: OTEL_SERVICE_NAME
          value: "otelcol"
        volumeMounts:
        - name: otel-collector-config
          mountPath: /etc/otelcol-contrib/otel-collector-config.yaml
          subPath: otel-collector-config.yaml
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
        livenessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: otel-collector-config
        configMap:
          name: otel-collector-config